import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ar');

  useEffect(() => {
    const saved = typeof window !== 'undefined' ? (localStorage.getItem('lang') || localStorage.getItem('app_lang')) : null;
    const initial = saved === 'en' ? 'en' : 'ar';
    setLang(initial);
    if (typeof document !== 'undefined') {
      document.documentElement.dir = initial === 'ar' ? 'rtl' : 'ltr';
    }
  }, []);

  useEffect(() => {
    if (typeof window !== 'undefined') localStorage.setItem('lang', lang);
    if (typeof document !== 'undefined') {
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    }
  }, [lang]);

  const toggleLang = () => setLang((prev) => (prev === 'ar' ? 'en' : 'ar'));

  const t = (key) => {
    const dict = {
      ar: {
        hello: 'مرحبًا',
        nada: 'ندى',
        login: 'تسجيل الدخول',
        signup: 'إنشاء حساب',
        loginSignup: 'تسجيل / إنشاء حساب',
        logout: 'تسجيل الخروج',
        cancel: 'إلغاء',
        backHome: 'العودة إلى الصفحة الرئيسية',
        aboutGym: 'نبذة عن النادي',
        facilitiesEquipment: 'المرافق والمعدات',
        availableFacilities: 'المرافق المتاحة',
        availableEquipment: 'المعدات المتاحة',
        contactInfo: 'معلومات الاتصال',
        workingHours: 'ساعات العمل',
        phoneNumber: 'رقم الهاتف',
        website: 'الموقع الإلكتروني',
        location: 'الموقع',
        interactiveMap: 'خريطة تفاعلية',
        comingSoon: 'قريباً',
        getDirections: 'الحصول على الاتجاهات',
        rating: 'تقييم',
        availableGyms: 'الأندية المتاحة',
        loadingGyms: 'جاري تحميل الأندية...',
        noResults: 'لم نجد أي نتائج',
        tryDifferentSearch: 'جرب البحث بكلمات مختلفة أو عدّل المرشحات',
        cantFindGym: 'لا تجد النادي المناسب؟',
        addGymsContinuously: 'نضيف أندية جديدة باستمرار. تواصل معنا لاقتراح نادي جديد.',
        contactUs: 'تواصل معنا',
        heroDescription: 'اكتشف أفضل الأندية الرياضية في الرياض واعثر على النادي المثالي لتحقيق أهدافك',
        noResultsTitle: 'لا توجد نتائج',
        tryDifferent: 'جرب البحث بكلمات مختلفة',
        searchPlaceholder: 'ابحث عن اسم النادي أو الموقع....',
        search: 'بحث',
        filter: 'تصفية',
        gymType: 'نوع النادي',
        men: 'رجال',
        women: 'سيدات',
        gender: 'الجنس',
        genderClassification: 'تصنيف الجنس',
        male: 'رجال',
        female: 'سيدات',
        mixed: 'مختلط',
        region: 'المنطقة',
        chooseRegion: 'اختر المنطقة',
        clearFilters: 'مسح الفلاتر',
        welcome: 'مرحبًا بك!',
        loginToAccount: 'سجل دخولك للوصول إلى حسابك',
        createNewAccount: 'إنشاء حساب جديد',
        createAccountToStart: 'أنشئ حساباً جديداً للبدء',
        verifyEmailTitle: 'تحقق من بريدك الإلكتروني',
        verifyCodeSent: 'تم إرسال رمز التحقق إلى',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        name: 'الاسم',
        fullName: 'الاسم الكامل',
        loginButton: 'تسجيل الدخول',
        forgotPassword: 'نسيت كلمة المرور؟',
        noAccount: 'ليس لديك حساب؟',
        createNewAccountLink: 'إنشاء حساب جديد',
        haveAccount: 'لديك حساب بالفعل؟',
        createAccount: 'إنشاء الحساب',
        verifyCode: 'رمز التحقق',
        confirmEmail: 'تأكيد البريد الإلكتروني',
        didntReceiveCode: 'لم تستلم الرمز؟',
        resendCode: 'إعادة إرسال الرمز',
        resendAfter: 'إعادة الإرسال بعد',
        seconds: 'ثانية',
        termsOfUse: 'شروط الاستخدام',
        privacyPolicy: 'سياسة الخصوصية',
        lastUpdated: 'آخر تحديث',
        backToHome: 'العودة للصفحة الرئيسية',
        contactUs: 'تواصل معنا',
        contactInfo: 'معلومات التواصل',
        sendMessage: 'أرسل لنا رسالة',
        message: 'الرسالة',
        messagePlaceholder: 'اكتب رسالتك هنا...',
        namePlaceholder: 'أدخل اسمك الكامل',
        sending: 'جاري الإرسال...',
        send: 'إرسال',
        messageSentSuccess: 'تم إرسال رسالتك بنجاح! سنتواصل معك قريباً.',
        messageSentError: 'حدث خطأ في إرسال الرسالة. حاول مرة أخرى.',
        forgotPassword: 'نسيت كلمة المرور؟',
        verifyYourEmail: 'تحقق من بريدك الإلكتروني',
        enterNewPassword: 'أدخل كلمة المرور الجديدة',
        newPassword: 'كلمة المرور الجديدة',
        confirmPassword: 'تأكيد كلمة المرور',
        changePassword: 'تغيير كلمة المرور',
        backToChangeEmail: '← العودة لتغيير البريد الإلكتروني',
        welcomeToDashboard: 'مرحبًا بك في لوحة التحكم',
        welcomeUser: 'مرحبًا',
        exploreGyms: 'يمكنك الآن استكشاف الأندية الرياضية',
        accountInfo: 'معلومات الحساب',
        quickActions: 'الإجراءات السريعة',
        exploreGymsLink: 'استكشاف الأندية',
        accountManagement: 'إدارة الحساب',
        backToHomepage: 'العودة للرئيسية',
        welcomeMessage: 'مرحبًا بك في GymFinder Riyadh!',
        accountCreatedSuccess: 'تم إنشاء حسابك بنجاح باستخدام رمز التحقق. يمكنك الآن استكشاف أفضل الأندية الرياضية في الرياض، مقارنة المرافق، واتخاذ القرار المناسب لتحقيق أهدافك الرياضية.',
        accountType: 'نوع الحساب',
        admin: 'مدير',
        user: 'مستخدم',
        aboutUs: 'من نحن',
        aboutUsDescription1: 'في مدينة تعجّ بالحياة والنشاط، جاءت منصتنا لتكون دليلك الذكي لاكتشاف الأندية الرياضية في الرياض بسهولة وسلاسة. نجمع لك مجموعة متنوعة من الأندية في مكان واحد، لتتعرّف على المرافق والخدمات المتوفّرة في كل نادٍ دون الحاجة للبحث المتعب.',
        aboutUsDescription2: 'نؤمن أن اختيار النادي المناسب هو خطوة أساسية نحو أسلوب حياة صحي ومتوازن، لذلك صمّمنا واجهة بسيطة وأنيقة تساعدك على تصفّح الأندية، ومقارنة المزايا، واختيار المكان الأنسب لك بكل راحة.',
        aboutUsVision: 'رؤيتنا هي بناء مجتمع يهتمّ بالرياضة والنشاط، ويعيش تجربة أفضل في كل تمرين وكل لحظة داخل النادي.',
        favoriteFood: 'اسم الطعام المفضل',
        favoriteFoodPlaceholder: 'أدخل اسم طعامك المفضل',
        favoriteFoodRequired: 'اسم الطعام المفضل مطلوب',
        favoriteFoodMinLength: 'اسم الطعام المفضل يجب أن يكون حرفين على الأقل',
        accountInformation: 'معلومات الحساب',
        myAccount: 'حسابي',
        management: 'الإدارة',
        loadMore: 'للمزيد',
      },
      en: {
        hello: 'Hello,',
        nada: 'Nada',
        login: 'Login',
        signup: 'Signup',
        loginSignup: 'Login / Signup',
        logout: 'Logout',
        cancel: 'Cancel',
        backHome: 'Back to Home',
        aboutGym: 'About the Gym',
        facilitiesEquipment: 'Facilities & Equipment',
        availableFacilities: 'Available Facilities',
        availableEquipment: 'Available Equipment',
        contactInfo: 'Contact Information',
        workingHours: 'Working Hours',
        phoneNumber: 'Phone Number',
        website: 'Website',
        location: 'Location',
        interactiveMap: 'Interactive Map',
        comingSoon: 'Coming Soon',
        getDirections: 'Get Directions',
        rating: 'ratings',
        availableGyms: 'Available Gyms',
        loadingGyms: 'Loading gyms...',
        noResults: 'No results found',
        tryDifferentSearch: 'Try searching with different words or adjust the filters',
        cantFindGym: "Can't find the right gym?",
        addGymsContinuously: 'We continuously add new gyms. Contact us to suggest a new gym.',
        contactUs: 'Contact Us',
        heroDescription: 'Discover the best gyms in Riyadh and find the perfect gym to achieve your goals',
        noResultsTitle: 'No results',
        tryDifferent: 'Try searching with different words',
        searchPlaceholder: 'Search for gym name or location....',
        search: 'Search',
        filter: 'Filter',
        gymType: 'Gym Type',
        men: 'Male',
        women: 'Female',
        gender: 'Gender',
        genderClassification: 'Gender Classification',
        male: 'Male',
        female: 'Female',
        mixed: 'Mixed',
        region: 'Region',
        chooseRegion: 'Choose Region',
        clearFilters: 'Clear Filters',
        welcome: 'Welcome!',
        loginToAccount: 'Log in to access your account',
        createNewAccount: 'Create New Account',
        createAccountToStart: 'Create a new account to get started',
        verifyEmailTitle: 'Verify Your Email',
        verifyCodeSent: 'Verification code sent to',
        email: 'Email',
        password: 'Password',
        name: 'Name',
        fullName: 'Full Name',
        loginButton: 'Log In',
        forgotPassword: 'Forgot Password?',
        noAccount: "Don't have an account?",
        createNewAccountLink: 'Create New Account',
        haveAccount: 'Already have an account?',
        createAccount: 'Create Account',
        verifyCode: 'Verification Code',
        confirmEmail: 'Confirm Email',
        didntReceiveCode: "Didn't receive the code?",
        resendCode: 'Resend Code',
        resendAfter: 'Resend after',
        seconds: 'seconds',
        termsOfUse: 'Terms of Use',
        privacyPolicy: 'Privacy Policy',
        lastUpdated: 'Last Updated',
        backToHome: 'Back to Home',
        contactUs: 'Contact Us',
        contactInfo: 'Contact Information',
        sendMessage: 'Send Us a Message',
        message: 'Message',
        messagePlaceholder: 'Write your message here...',
        namePlaceholder: 'Enter your full name',
        sending: 'Sending...',
        send: 'Send',
        messageSentSuccess: 'Your message has been sent successfully! We will contact you soon.',
        messageSentError: 'An error occurred while sending the message. Please try again.',
        forgotPassword: 'Forgot Password?',
        verifyYourEmail: 'Verify Your Email',
        enterNewPassword: 'Enter New Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        changePassword: 'Change Password',
        backToChangeEmail: '← Back to Change Email',
        welcomeToDashboard: 'Welcome to Dashboard',
        welcomeUser: 'Welcome',
        exploreGyms: 'You can now explore gyms',
        accountInfo: 'Account Information',
        quickActions: 'Quick Actions',
        exploreGymsLink: 'Explore Gyms',
        accountManagement: 'Account Management',
        backToHomepage: 'Back to Home',
        welcomeMessage: 'Welcome to GymFinder Riyadh!',
        accountCreatedSuccess: 'Your account has been successfully created using the verification code. You can now explore the best gyms in Riyadh, compare facilities, and make the right decision to achieve your fitness goals.',
        accountType: 'Account Type',
        admin: 'Admin',
        user: 'User',
        aboutUs: 'About Us',
        aboutUsDescription1: 'In a city full of life and activity, our platform came to be your smart guide to discovering sports gyms in Riyadh with ease and smoothness. We gather for you a diverse collection of gyms in one place, so you can learn about the facilities and services available in each gym without the need for tiring searching.',
        aboutUsDescription2: 'We believe that choosing the right gym is a fundamental step towards a healthy and balanced lifestyle, so we designed a simple and elegant interface that helps you browse gyms, compare features, and choose the most suitable place for you with complete comfort.',
        aboutUsVision: 'Our vision is to build a community that cares about sports and activity, and to live a better experience in every workout and every moment inside the gym.',
        favoriteFood: 'Favorite Food',
        favoriteFoodPlaceholder: 'Enter your favorite food',
        favoriteFoodRequired: 'Favorite food is required',
        favoriteFoodMinLength: 'Favorite food must be at least 2 characters',
        accountInformation: 'Account Information',
        myAccount: 'My Account',
        management: 'Management',
        loadMore: 'More',
      },
    };
    return (dict[lang] && dict[lang][key]) || key;
  };

  const value = useMemo(() => ({ lang, toggleLang, t }), [lang]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}


